"""added gender and age fields

Revision ID: 9037e2bd3e3d
Revises: 5115c7d85766
Create Date: 2025-12-06 18:58:39.247953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9037e2bd3e3d'
down_revision = '5115c7d85766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
